import {readFileSync, writeFileSync} from 'node:fs'
import {dirname, join, relative, resolve} from 'node:path'
import {fileURLToPath} from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const manifestPath = join(root, 'bundle.sources.json')
const output = join(root, 'l.js')
const sourceNames = JSON.parse(readFileSync(manifestPath, 'utf8'))

if (!Array.isArray(sourceNames) || !sourceNames.length) {
    throw new Error('bundle.sources.json must contain a non-empty array')
}

if (new Set(sourceNames).size !== sourceNames.length) {
    throw new Error('bundle.sources.json contains duplicate sources')
}

const sources = sourceNames.map((name) => {
    const source = resolve(root, name)
    const localName = relative(root, source)

    if (localName.startsWith('..') || localName === 'l.js') {
        throw new Error(`Invalid bundle source: ${name}`)
    }

    return {name: localName, code: readFileSync(source, 'utf8').trim()}
})

const banner = [
    '/*',
    ' * Lampa custom bundle for darkworon',
    ' * Generated by lampa-plugins/build.mjs. Do not edit directly.',
    ` * Sources: ${sources.map((source) => source.name).join(', ')}`,
    ' */',
    ''
].join('\n')

const body = sources.map((source) => {
    return `;\n/* source: ${source.name} */\n${source.code}`
}).join('\n\n')

const bundle = `${banner}${body}\n`

new Function(bundle)
writeFileSync(output, bundle)

console.log(`Built ${relative(process.cwd(), output)} from ${sources.length} sources`)
