/*
 * Lampa custom bundle for darkworon
 * Generated by lampa-plugins/build.mjs. Do not edit directly.
 * Sources: adblock/plugin.js, torrserver-subtitles/plugin.js, english-tracks/plugin.js
 */
;
/* source: adblock/plugin.js */
(function () {
    'use strict'

    var PLUGIN_NAME = 'Lampa AdBlock'
    var PLUGIN_VERSION = '1.0.0'
    var SETTING_NAME = 'lampa_adblock_enabled'
    var AD_ENDPOINT = /\/api\/ad\/get\/(?:preroll|banner)(?:[/?#]|$)/i
    var VAST_FIELDS = [
        'vast_url',
        'vast_api',
        'vast_msg',
        'vast_region',
        'vast_platform',
        'vast_screen'
    ]

    if (window.LampaAdBlock) return

    var state = {
        version: PLUGIN_VERSION,
        blockedRequests: 0,
        strippedPlayers: 0,
        removedElements: 0,
        transportInstalled: false,
        playerHookInstalled: false,
        settingsInstalled: false
    }

    window.LampaAdBlock = state

    function enabled() {
        try {
            if (window.Lampa && Lampa.Storage) {
                return Lampa.Storage.get(SETTING_NAME, 'true') !== false
            }

            return window.localStorage.getItem(SETTING_NAME) !== 'false'
        }
        catch (error) {
            return true
        }
    }

    function setNativeFlag() {
        try {
            if (!window.lampa_settings) return

            window.lampa_settings.disable_features = window.lampa_settings.disable_features || {}
            window.lampa_settings.disable_features.ads = enabled()
        }
        catch (error) {}
    }

    function isAdvertEndpoint(url) {
        return AD_ENDPOINT.test(String(url || ''))
    }

    function installAjaxTransport() {
        var jq = window.jQuery || window.$

        if (state.transportInstalled || !jq || typeof jq.ajaxTransport !== 'function') return false

        jq.ajaxTransport('+*', function (options) {
            if (!enabled() || !isAdvertEndpoint(options.url)) return

            var timer = null

            return {
                send: function (headers, complete) {
                    state.blockedRequests++

                    timer = setTimeout(function () {
                        complete(
                            200,
                            'success',
                            {
                                json: {ad: []},
                                text: '{"ad":[]}'
                            },
                            'Content-Type: application/json\r\n'
                        )
                    }, 0)
                },
                abort: function () {
                    clearTimeout(timer)
                }
            }
        })

        state.transportInstalled = true

        return true
    }

    function stripVastData(event) {
        if (!enabled() || !event || !event.data) return

        var stripped = false

        VAST_FIELDS.forEach(function (field) {
            if (Object.prototype.hasOwnProperty.call(event.data, field)) {
                delete event.data[field]
                stripped = true
            }
        })

        if (stripped) state.strippedPlayers++
    }

    function installPlayerHook() {
        if (state.playerHookInstalled) return true
        if (!window.Lampa || !Lampa.Player || !Lampa.Player.listener) return false
        if (typeof Lampa.Player.listener.follow !== 'function') return false

        Lampa.Player.listener.follow('create', stripVastData)
        state.playerHookInstalled = true

        return true
    }

    function isOfficialBannerContainer(element) {
        if (!element || element.nodeType !== 1 || element.tagName !== 'DIV') return false
        if (!element.parentElement || !element.parentElement.classList.contains('player')) return false

        var style = element.style

        return style.position === 'absolute' &&
            style.top === '0px' &&
            style.left === '0px' &&
            style.width === '100%' &&
            style.height === '100%' &&
            style.zIndex === '10' &&
            style.pointerEvents === 'none'
    }

    function removeElement(element) {
        if (!element || !element.parentNode) return

        element.parentNode.removeChild(element)
        state.removedElements++
    }

    function cleanupAds() {
        if (!enabled() || !document.querySelectorAll) return

        Array.prototype.forEach.call(document.querySelectorAll('.ad-preroll'), removeElement)

        Array.prototype.forEach.call(document.querySelectorAll('.player > div'), function (element) {
            if (isOfficialBannerContainer(element)) removeElement(element)
        })
    }

    function installStyle() {
        if (document.getElementById('lampa-adblock-style')) return

        var style = document.createElement('style')
        style.id = 'lampa-adblock-style'
        style.textContent = [
            '.ad-preroll,',
            '.player .ima-ad-container,',
            '.player [id^="google_ads_iframe_"],',
            '.player iframe[src*="doubleclick.net"],',
            '.player iframe[src*="googlesyndication.com"] {',
            '    display: none !important;',
            '    visibility: hidden !important;',
            '    pointer-events: none !important;',
            '}'
        ].join('\n')

        ;(document.head || document.documentElement).appendChild(style)
    }

    function installObserver() {
        if (!window.MutationObserver || !document.documentElement) return

        var pending = false
        var schedule = window.requestAnimationFrame || function (callback) {
            return setTimeout(callback, 16)
        }

        var observer = new MutationObserver(function () {
            if (pending || !enabled()) return

            pending = true

            schedule(function () {
                pending = false
                cleanupAds()
            })
        })

        observer.observe(document.documentElement, {
            childList: true,
            subtree: true
        })

        state.observer = observer
    }

    function installSettings() {
        if (state.settingsInstalled || !window.Lampa || !Lampa.SettingsApi) return false

        Lampa.SettingsApi.addParam({
            component: 'more',
            param: {
                name: SETTING_NAME,
                type: 'trigger',
                default: true
            },
            field: {
                name: 'Блокировать рекламу',
                description: 'Preroll между эпизодами и баннер в плеере'
            },
            onChange: function () {
                setNativeFlag()

                if (enabled()) cleanupAds()

                setTimeout(function () {
                    window.location.reload()
                }, 300)
            }
        })

        state.settingsInstalled = true

        return true
    }

    function onReady() {
        installSettings()
        cleanupAds()
    }

    state.enabled = enabled
    state.isAdvertEndpoint = isAdvertEndpoint
    state.cleanup = cleanupAds

    setNativeFlag()
    installAjaxTransport()
    installPlayerHook()
    installStyle()
    installObserver()

    if (window.appready) onReady()
    else if (window.Lampa && Lampa.Listener && typeof Lampa.Listener.follow === 'function') {
        Lampa.Listener.follow('app', function (event) {
            if (event.type === 'ready') onReady()
        })
    }

    console.log(PLUGIN_NAME, 'started', PLUGIN_VERSION)
})()

;
/* source: torrserver-subtitles/plugin.js */
(function () {
    'use strict'

    var PLUGIN_NAME = 'TorrServer Subtitles'
    var PLUGIN_VERSION = '1.0.0'
    var SETTING_NAME = 'torrserver_subtitles_lampa_style'
    var STYLE_ID = 'torrserver-subtitles-native-style'
    var SUBTITLE_SETTINGS = [
        'subtitles_size',
        'subtitles_stroke',
        'subtitles_backdrop',
        'player_subs_shift_time'
    ]

    if (window.LampaTorrserverSubtitles) return

    var session = null
    var latestPlayerData = null

    var state = {
        version: PLUGIN_VERSION,
        active: false,
        nativeTracks: 0,
        bridgedTracks: 0,
        renderedFrames: 0,
        settingsInstalled: false
    }

    window.LampaTorrserverSubtitles = state

    function enabled() {
        try {
            if (window.Lampa && Lampa.Storage) {
                return Lampa.Storage.get(SETTING_NAME, 'true') !== false
            }

            return window.localStorage.getItem(SETTING_NAME) !== 'false'
        }
        catch (error) {
            return true
        }
    }

    function storageValue(name, fallback) {
        try {
            return window.Lampa && Lampa.Storage ? Lampa.Storage.get(name, fallback) : fallback
        }
        catch (error) {
            return fallback
        }
    }

    function storageField(name, fallback) {
        try {
            var value = window.Lampa && Lampa.Storage ? Lampa.Storage.field(name) : fallback

            return typeof value === 'undefined' || value === '' ? fallback : value
        }
        catch (error) {
            return fallback
        }
    }

    function asBoolean(value) {
        return value === true || value === 'true' || value === 1 || value === '1'
    }

    function isTorrentPlayback(data) {
        if (!data) return false
        if (data.torrent_hash) return true

        try {
            var server = window.Lampa && Lampa.Torserver ? Lampa.Torserver.ip() : ''
            var url = String(data.url || '')

            return Boolean(server && url.indexOf(server) !== -1 && /\/(?:stream|gst)\//i.test(url))
        }
        catch (error) {
            return false
        }
    }

    function videoElement() {
        try {
            return window.Lampa && Lampa.PlayerVideo ? Lampa.PlayerVideo.video() : null
        }
        catch (error) {
            return null
        }
    }

    function subtitleContainer() {
        try {
            var render = window.Lampa && Lampa.PlayerVideo ? Lampa.PlayerVideo.render() : null

            return render && render.find ? render.find('.player-video__subtitles') : null
        }
        catch (error) {
            return null
        }
    }

    function dispatchSubtitle(text, force) {
        if (!session || !session.video) return
        if (!force && session.lastText === text) return

        session.lastText = text

        var event

        try {
            event = new Event('subtitle')
        }
        catch (error) {
            event = document.createEvent('Event')
            event.initEvent('subtitle', false, false)
        }

        event.text = text
        session.video.dispatchEvent(event)

        state.renderedFrames++
    }

    function clearSubtitle() {
        if (!session || session.lastText === '') return

        dispatchSubtitle('', true)
    }

    function escapeText(text) {
        var element = document.createElement('div')
        element.textContent = String(text || '')

        return element.innerHTML.replace(/\r?\n/g, '<br>')
    }

    function cueHtml(cue) {
        if (!cue) return ''

        try {
            if (typeof cue.getCueAsHTML === 'function') {
                var wrapper = document.createElement('div')
                var fragment = cue.getCueAsHTML()

                wrapper.appendChild(fragment)

                return wrapper.innerHTML.replace(/\r?\n/g, '<br>')
            }
        }
        catch (error) {}

        return escapeText(cue.text)
    }

    function cuesAt(track, time) {
        var result = []
        var cues = track && track.cues

        if (cues) {
            for (var index = 0; index < cues.length; index++) {
                var cue = cues[index]

                if (cue.startTime > time) break
                if (cue.startTime <= time && time < cue.endTime) result.push(cue)
            }

            return result
        }

        var active = track && track.activeCues

        if (active) {
            for (var position = 0; position < active.length; position++) result.push(active[position])
        }

        return result
    }

    function shiftedTime() {
        if (!session || !session.video) return 0

        var shift = parseInt(storageValue('player_subs_shift_time', '0'), 10)

        return session.video.currentTime - (isNaN(shift) ? 0 : shift)
    }

    function renderCurrent(force) {
        if (!session || !session.track || !enabled()) return

        var cues = cuesAt(session.track, shiftedTime())
        var text = cues.map(cueHtml).filter(Boolean).join('<br>')
        var container = subtitleContainer()

        if (container && container.removeClass) container.removeClass('hide')

        dispatchSubtitle(text, force)
    }

    function trackSupportsBridge(track) {
        return track && ('cues' in track || 'activeCues' in track)
    }

    function activateTrack(track) {
        if (!session || !track || !trackSupportsBridge(track)) return false

        if (session.track !== track) {
            session.track = track
            session.lastText = null
            state.bridgedTracks++
        }

        try {
            track.selected = true
            track.mode = 'hidden'
        }
        catch (error) {
            return false
        }

        if (track.mode !== 'hidden') return false

        renderCurrent(true)

        return true
    }

    function deactivateTrack() {
        if (!session || !session.track) return

        session.track = null
        clearSubtitle()
    }

    function scanTracks() {
        if (!session || session.scanning || !enabled()) return

        session.scanning = true

        try {
            var tracks = session.video.textTracks
            var showing = null

            state.nativeTracks = tracks ? tracks.length : 0

            if (tracks) {
                for (var index = 0; index < tracks.length; index++) {
                    if (tracks[index].mode === 'showing') {
                        showing = tracks[index]
                        break
                    }
                }
            }

            if (showing) activateTrack(showing)
            else if (session.track && session.track.mode === 'hidden') renderCurrent(false)
            else deactivateTrack()
        }
        finally {
            session.scanning = false
        }
    }

    function bind(target, eventName, callback) {
        if (!target || typeof target.addEventListener !== 'function') return

        target.addEventListener(eventName, callback)
        session.listeners.push([target, eventName, callback])
    }

    function removeListeners() {
        if (!session) return

        session.listeners.forEach(function (item) {
            item[0].removeEventListener(item[1], item[2])
        })

        session.listeners = []
    }

    function restoreNativeTrack() {
        if (!session || !session.track) return

        try {
            if (session.track.mode === 'hidden' && session.track.selected) {
                session.track.mode = 'showing'
            }
        }
        catch (error) {}
    }

    function stop(restoreNative) {
        if (!session) {
            state.active = false
            return
        }

        clearInterval(session.interval)
        removeListeners()

        if (restoreNative) restoreNativeTrack()

        clearSubtitle()

        session = null
        state.active = false
    }

    function start(data) {
        latestPlayerData = data || latestPlayerData

        stop(false)

        if (!enabled() || !isTorrentPlayback(latestPlayerData)) return

        var video = videoElement()

        if (!video || !video.textTracks) return

        session = {
            video: video,
            track: null,
            lastText: null,
            scanning: false,
            listeners: [],
            interval: null
        }

        state.active = true

        bind(video, 'timeupdate', scanTracks)
        bind(video, 'seeking', scanTracks)
        bind(video, 'seeked', scanTracks)
        bind(video, 'loadedmetadata', scanTracks)
        bind(video, 'loadeddata', scanTracks)
        bind(video.textTracks, 'change', scanTracks)
        bind(video.textTracks, 'addtrack', scanTracks)
        bind(video.textTracks, 'removetrack', scanTracks)

        session.interval = setInterval(scanTracks, 250)

        setTimeout(scanTracks, 0)
        setTimeout(updateNativeCueStyle, 0)
    }

    function updateNativeCueStyle() {
        var style = document.getElementById(STYLE_ID)

        if (!style) {
            style = document.createElement('style')
            style.id = STYLE_ID
            ;(document.head || document.documentElement).appendChild(style)
        }

        if (!enabled()) {
            style.textContent = ''
            return
        }

        var size = storageField('subtitles_size', 'normal')
        var fallbackSizes = {small: '2em', normal: '2.5em', large: '3em'}
        var container = document.querySelector('.player-video__subtitles')
        var computedSize = container && window.getComputedStyle ? window.getComputedStyle(container).fontSize : ''
        var fontSize = computedSize || fallbackSizes[size] || fallbackSizes.normal
        var backdrop = asBoolean(storageField('subtitles_backdrop', false))
        var stroke = asBoolean(storageField('subtitles_stroke', false))

        style.textContent = [
            '.player-video__video::cue {',
            '    color: #fff !important;',
            '    font-size: ' + fontSize + ' !important;',
            '    font-weight: 600 !important;',
            '    line-height: 1.25 !important;',
            '    background-color: ' + (backdrop ? 'rgba(0, 0, 0, .55)' : 'transparent') + ' !important;',
            '    text-shadow: ' + (stroke ? '0 2px 1px #000, 0 -2px 1px #000, -2px 1px 0 #000, 2px 0 1px #000' : 'none') + ' !important;',
            '}'
        ].join('\n')
    }

    function applySetting() {
        updateNativeCueStyle()

        if (enabled()) start(latestPlayerData)
        else stop(true)
    }

    function installSettings() {
        if (state.settingsInstalled || !window.Lampa || !Lampa.SettingsApi) return

        Lampa.SettingsApi.addParam({
            component: 'more',
            param: {
                name: SETTING_NAME,
                type: 'trigger',
                default: true
            },
            field: {
                name: 'Оформлять torrent-субтитры как в Lampa',
                description: 'Размер, фон, обводка и сдвиг времени для встроенных дорожек'
            },
            onChange: function () {
                setTimeout(applySetting, 0)
            }
        })

        state.settingsInstalled = true
    }

    function ready() {
        installSettings()
        updateNativeCueStyle()

        try {
            if (Lampa.Player.opened()) start(Lampa.Player.playdata())
        }
        catch (error) {}
    }

    state.enabled = enabled
    state.isTorrentPlayback = isTorrentPlayback
    state.scan = scanTracks
    state.stop = function () {
        stop(true)
    }

    if (window.Lampa && Lampa.Player && Lampa.Player.listener) {
        Lampa.Player.listener.follow('ready', start)
        Lampa.Player.listener.follow('destroy', function () {
            latestPlayerData = null
            stop(false)
        })
    }

    if (window.Lampa && Lampa.Storage && Lampa.Storage.listener) {
        Lampa.Storage.listener.follow('change', function (event) {
            if (SUBTITLE_SETTINGS.indexOf(event.name) === -1) return

            setTimeout(function () {
                updateNativeCueStyle()
                renderCurrent(true)
            }, 0)
        })
    }

    if (window.appready) ready()
    else if (window.Lampa && Lampa.Listener && Lampa.Listener.follow) {
        Lampa.Listener.follow('app', function (event) {
            if (event.type === 'ready') ready()
        })
    }

    console.log(PLUGIN_NAME, 'started', PLUGIN_VERSION)
})()

;
/* source: english-tracks/plugin.js */
(function () {
    'use strict'

    var PLUGIN_NAME = 'Lampa English Tracks'
    var PLUGIN_VERSION = '1.0.0'
    var SETTING_ENABLED = 'english_tracks_enabled'
    var SETTING_REMEMBER = 'english_tracks_remember'
    var PREFERENCES_KEY = 'english_tracks_preferences'
    var MAX_PREFERENCES = 200

    if (window.LampaEnglishTracks) return

    var current = null
    var settingsInstalled = false

    var state = {
        version: PLUGIN_VERSION,
        audioSelections: 0,
        subtitleSelections: 0,
        savedPreferences: 0,
        restoredPreferences: 0
    }

    window.LampaEnglishTracks = state

    function storageGet(name, fallback) {
        try {
            return window.Lampa && Lampa.Storage ? Lampa.Storage.get(name, fallback) : fallback
        }
        catch (error) {
            return fallback
        }
    }

    function storageSet(name, value) {
        try {
            if (window.Lampa && Lampa.Storage) Lampa.Storage.set(name, value)
        }
        catch (error) {}
    }

    function enabled() {
        return storageGet(SETTING_ENABLED, 'true') !== false
    }

    function remember() {
        return storageGet(SETTING_REMEMBER, 'true') !== false
    }

    function normalize(value) {
        var text = String(value || '').toLowerCase().replace(/<[^>]*>/g, ' ')

        try {
            text = text.normalize('NFD').replace(/[\u0300-\u036f]/g, '')
        }
        catch (error) {}

        return text
            .replace(/ё/g, 'е')
            .replace(/[^a-zа-я0-9]+/g, ' ')
            .replace(/^\s+|\s+$/g, '')
            .replace(/\s+/g, ' ')
    }

    function firstValue(values) {
        for (var i = 0; i < values.length; i++) {
            if (values[i] !== undefined && values[i] !== null && String(values[i]).trim()) {
                return String(values[i])
            }
        }

        return ''
    }

    function tokens(value) {
        var text = normalize(value)

        return text ? text.split(' ') : []
    }

    function hasToken(value, variants) {
        var list = tokens(value)

        return variants.some(function (variant) {
            return list.indexOf(variant) !== -1
        })
    }

    function hasStem(value, variants) {
        var list = tokens(value)

        return variants.some(function (variant) {
            return list.some(function (item) {
                return item.indexOf(variant) === 0
            })
        })
    }

    function canonicalLanguage(value) {
        var text = normalize(value)
        var list = tokens(text)

        if (list.some(function (item) {
            return ['en', 'eng', 'english'].indexOf(item) !== -1
        }) || hasStem(text, ['англ'])) return 'en'

        if (list.some(function (item) {
            return ['ru', 'rus', 'russian', 'рус'].indexOf(item) !== -1
        }) || hasStem(text, ['русск'])) return 'ru'

        if (list.some(function (item) {
            return ['uk', 'ukr', 'ukrainian'].indexOf(item) !== -1
        }) || hasStem(text, ['украинск'])) return 'uk'

        if (list.some(function (item) {
            return ['es', 'spa', 'spanish'].indexOf(item) !== -1
        }) || hasStem(text, ['испанск'])) return 'es'

        if (list.some(function (item) {
            return ['fr', 'fra', 'fre', 'french'].indexOf(item) !== -1
        }) || hasStem(text, ['французск'])) return 'fr'

        if (list.some(function (item) {
            return ['de', 'deu', 'ger', 'german'].indexOf(item) !== -1
        }) || hasStem(text, ['немецк'])) return 'de'

        if (list.length === 1 && /^[a-z]{2,3}$/.test(list[0])) return list[0]

        return text
    }

    function toArray(list) {
        if (!list) return []
        if (Array.isArray(list)) return list

        var result = []
        var length = typeof list.length === 'number' ? list.length : 0

        for (var i = 0; i < length; i++) result.push(list[i])

        return result
    }

    function activityMovie() {
        var activity = storageGet('activity', '{}')

        return activity && activity.movie ? activity.movie : {}
    }

    function movieFromData(data) {
        return data && data.card ? data.card : activityMovie()
    }

    function originalLanguage() {
        var movie = movieFromData(current ? current.data : null)

        return canonicalLanguage(movie.original_language || movie.language || '')
    }

    function contentKey(data) {
        data = data || {}

        var movie = movieFromData(data)
        var id = movie.id || movie.imdb_id || movie.kinopoisk_id
        var type = movie.original_name || movie.name ? 'tv' : 'movie'

        if (id) return type + ':' + id
        if (data.torrent_hash) return 'torrent:' + data.torrent_hash

        var title = firstValue([
            movie.original_title,
            movie.original_name,
            movie.title,
            movie.name,
            data.first_title,
            data.title
        ])

        title = normalize(title)
            .replace(/\bs\d+e\d+\b/g, '')
            .replace(/\bseason\s*\d+\b/g, '')
            .replace(/\bepisode\s*\d+\b/g, '')
            .replace(/\s+/g, ' ')
            .replace(/^\s+|\s+$/g, '')

        return title ? 'title:' + title : ''
    }

    function translation(kind, index) {
        var data = current ? current.data : null
        var translate = data && data.translate
        var list = translate && typeof translate === 'object'
            ? translate[kind === 'audio' ? 'tracks' : 'subs']
            : null

        return Array.isArray(list) && list[index] ? list[index] : {}
    }

    function descriptor(item, index, kind) {
        item = item || {}

        var translationIndex = kind === 'subtitles' && item.index !== undefined && item.index >= 0
            ? item.index
            : index
        var extra = translation(kind, translationIndex)
        var languageSource = firstValue([
            item.language,
            item.lang,
            item.srclang,
            extra.language,
            extra.lang,
            extra.srclang
        ])
        var labelSource = firstValue([item.label, extra.label])
        var nameSource = firstValue([item.name, extra.name])
        var titleSource = firstValue([item.title, extra.title])
        var text = normalize([
            languageSource,
            labelSource,
            nameSource,
            titleSource,
            extra.language,
            extra.label,
            extra.name
        ].join(' '))

        var language = canonicalLanguage(languageSource)

        if (!language || language === 'und') language = canonicalLanguage(text)

        return {
            index: item.index !== undefined && item.index !== null ? item.index : index,
            language: language,
            label: normalize(labelSource),
            name: normalize(nameSource),
            text: text.slice(0, 240)
        }
    }

    function isOriginal(value) {
        return hasToken(value, ['original', 'originals', 'оригинал', 'оригинальная', 'оригинальный'])
    }

    function englishScore(item, index, kind) {
        if (!item || item.index === -1) return -1

        var info = descriptor(item, index, kind)
        var score = 0

        if (info.language === 'en') score += 500
        if (canonicalLanguage(info.text) === 'en') score += 350
        if (originalLanguage() === 'en' && isOriginal(info.text)) score += 240

        if (kind === 'subtitles') {
            if (hasToken(info.text, ['full', 'complete', 'полные', 'полный'])) score += 35
            if (hasToken(info.text, ['forced', 'force', 'форсированные', 'надписи'])) score -= 25
            if (hasToken(info.text, ['signs', 'songs'])) score -= 15
        }
        else {
            if (hasToken(info.text, ['commentary', 'comments', 'комментарии'])) score -= 80
            if (hasToken(info.text, ['description', 'descriptive', 'audiodescription', 'тифлокомментарий'])) score -= 80
        }

        return score
    }

    function englishCandidate(items, kind) {
        var bestIndex = -1
        var bestScore = 0

        items.forEach(function (item, index) {
            var score = englishScore(item, index, kind)

            if (score > bestScore) {
                bestScore = score
                bestIndex = index
            }
        })

        return bestIndex
    }

    function loadPreferences() {
        var preferences = storageGet(PREFERENCES_KEY, '{}')

        return preferences && typeof preferences === 'object' && !Array.isArray(preferences)
            ? preferences
            : {}
    }

    function preference(kind) {
        if (!remember() || !current || !current.key) return null

        var entry = loadPreferences()[current.key]

        return entry && entry[kind] ? entry[kind] : null
    }

    function preferenceCandidate(items, kind, saved) {
        if (!saved) return -1
        if (saved.off) return -2

        var bestIndex = -1
        var bestScore = -1

        items.forEach(function (item, index) {
            if (!item || item.index === -1) return

            var info = descriptor(item, index, kind)
            var score = 0

            if (saved.language && info.language === saved.language) score += 400
            if (saved.label && info.label === saved.label) score += 260
            if (saved.name && info.name === saved.name) score += 260
            if (saved.text && info.text === saved.text) score += 320
            if (saved.index !== undefined && info.index === saved.index) score += 20

            if (score > bestScore) {
                bestScore = score
                bestIndex = index
            }
        })

        if (bestScore >= 200) return bestIndex
        if (bestScore >= 20 && !saved.language && !saved.label && !saved.name && !saved.text) return bestIndex

        return -1
    }

    function setProperty(item, name, value) {
        try {
            item[name] = value
        }
        catch (error) {}
    }

    function disableAudio(items) {
        items.forEach(function (item) {
            setProperty(item, 'enabled', false)
            setProperty(item, 'selected', false)
        })
    }

    function disableSubtitles(items) {
        items.forEach(function (item) {
            if (item.index !== -1) setProperty(item, 'mode', 'disabled')
            setProperty(item, 'selected', false)
        })
    }

    function showSubtitles(status) {
        try {
            if (window.Lampa && Lampa.PlayerVideo && typeof Lampa.PlayerVideo.subsview === 'function') {
                Lampa.PlayerVideo.subsview(status)
            }
        }
        catch (error) {}
    }

    function applyAudio(items) {
        if (!enabled() || !items.length) return

        var saved = preference('audio')
        var index = preferenceCandidate(items, 'audio', saved)

        if (index >= 0) state.restoredPreferences++
        else index = englishCandidate(items, 'audio')

        if (index < 0 || !items[index]) return

        disableAudio(items)
        setProperty(items[index], 'enabled', true)
        setProperty(items[index], 'selected', true)

        state.audioSelections++
        state.lastAudio = descriptor(items[index], index, 'audio')
    }

    function applySubtitles(items) {
        if (!enabled() || !items.length) return

        var saved = preference('subtitles')
        var index = preferenceCandidate(items, 'subtitles', saved)

        if (index === -2) {
            disableSubtitles(items)
            showSubtitles(false)
            state.restoredPreferences++
            state.lastSubtitles = {off: true}
            return
        }

        if (index >= 0) state.restoredPreferences++
        else index = englishCandidate(items, 'subtitles')

        if (index < 0 || !items[index]) return

        disableSubtitles(items)
        setProperty(items[index], 'mode', 'showing')
        setProperty(items[index], 'selected', true)
        showSubtitles(true)

        state.subtitleSelections++
        state.lastSubtitles = descriptor(items[index], index, 'subtitles')
    }

    function trimPreferences(preferences) {
        var keys = Object.keys(preferences)

        if (keys.length <= MAX_PREFERENCES) return

        keys.sort(function (left, right) {
            return (preferences[right].updated || 0) - (preferences[left].updated || 0)
        })

        keys.slice(MAX_PREFERENCES).forEach(function (key) {
            delete preferences[key]
        })
    }

    function savePreference(kind, value) {
        if (!remember() || !current || !current.key || !value) return

        var preferences = loadPreferences()
        var entry = preferences[current.key] || {}
        var previous = entry[kind]

        if (JSON.stringify(previous || null) === JSON.stringify(value)) return

        entry[kind] = value
        entry.updated = Date.now()
        preferences[current.key] = entry

        trimPreferences(preferences)
        storageSet(PREFERENCES_KEY, preferences)

        state.savedPreferences++
    }

    function selectedAudio(items) {
        for (var i = 0; i < items.length; i++) {
            try {
                if (items[i].selected === true || items[i].enabled === true) return i
            }
            catch (error) {}
        }

        return -1
    }

    function selectedSubtitles(items) {
        for (var i = 0; i < items.length; i++) {
            try {
                if (items[i].index === -1 && items[i].selected === true) return -2
                if (items[i].selected === true || items[i].mode === 'showing') return i
            }
            catch (error) {}
        }

        return -1
    }

    function compactDescriptor(item, index, kind) {
        var info = descriptor(item, index, kind)

        return {
            index: info.index,
            language: info.language,
            label: info.label,
            name: info.name,
            text: info.text
        }
    }

    function captureSelections() {
        if (!enabled() || !remember() || !current) return

        if (current.tracks && current.tracks.length) {
            var audioIndex = selectedAudio(current.tracks)

            if (audioIndex >= 0) {
                savePreference('audio', compactDescriptor(current.tracks[audioIndex], audioIndex, 'audio'))
            }
        }

        if (current.subtitles && current.subtitles.length) {
            var subtitleIndex = selectedSubtitles(current.subtitles)

            if (subtitleIndex === -2) savePreference('subtitles', {off: true})
            else if (subtitleIndex >= 0) {
                savePreference('subtitles', compactDescriptor(current.subtitles[subtitleIndex], subtitleIndex, 'subtitles'))
            }
        }
    }

    function beginPlayback(data) {
        captureSelections()

        current = {
            data: data || {},
            key: contentKey(data || {}),
            tracks: null,
            subtitles: null
        }

        state.currentKey = current.key
    }

    function updatePlayback(data) {
        if (!current) beginPlayback(data)
        else {
            current.data = data || current.data
            current.key = contentKey(current.data)
            state.currentKey = current.key
        }

        if (data && Array.isArray(data.voiceovers)) {
            current.tracks = data.voiceovers
            applyAudio(current.tracks)
        }
    }

    function onTracks(event) {
        if (!current) updatePlayback(Lampa.Player.playdata ? Lampa.Player.playdata() : {})

        current.tracks = toArray(event && event.tracks)
        applyAudio(current.tracks)
    }

    function onSubtitles(event) {
        if (!current) updatePlayback(Lampa.Player.playdata ? Lampa.Player.playdata() : {})

        current.subtitles = toArray(event && event.subs)
        applySubtitles(current.subtitles)
    }

    function onVideoDestroy() {
        captureSelections()

        if (current) {
            current.tracks = null
            current.subtitles = null
        }
    }

    function onPlayerDestroy() {
        captureSelections()
        current = null
        state.currentKey = ''
    }

    function clearPreferences() {
        storageSet(PREFERENCES_KEY, {})

        if (current) {
            current.lastAudio = null
            current.lastSubtitles = null
        }

        if (window.Lampa && Lampa.Noty) Lampa.Noty.show('Сохранённые дорожки очищены')
    }

    function installSettings() {
        if (settingsInstalled || !window.Lampa || !Lampa.SettingsApi) return false

        Lampa.SettingsApi.addParam({
            component: 'more',
            param: {type: 'title'},
            field: {name: 'English Tracks'}
        })

        Lampa.SettingsApi.addParam({
            component: 'more',
            param: {
                name: SETTING_ENABLED,
                type: 'trigger',
                default: true
            },
            field: {
                name: 'Английские дорожки по умолчанию',
                description: 'Аудио и полные субтитры при запуске плеера'
            }
        })

        Lampa.SettingsApi.addParam({
            component: 'more',
            param: {
                name: SETTING_REMEMBER,
                type: 'trigger',
                default: true
            },
            field: {
                name: 'Запоминать ручной выбор',
                description: 'Отдельно для каждого фильма или сериала'
            }
        })

        Lampa.SettingsApi.addParam({
            component: 'more',
            param: {
                name: 'english_tracks_reset',
                type: 'button'
            },
            field: {name: 'Очистить сохранённые дорожки'},
            onChange: clearPreferences
        })

        settingsInstalled = true

        return true
    }

    function installHooks() {
        if (!window.Lampa || !Lampa.Player || !Lampa.PlayerVideo) return false

        Lampa.Player.listener.follow('create', function (event) {
            beginPlayback(event && event.data)
        })
        Lampa.Player.listener.follow('start', updatePlayback)
        Lampa.Player.listener.follow('destroy', onPlayerDestroy)

        Lampa.PlayerVideo.listener.follow('tracks', onTracks)
        Lampa.PlayerVideo.listener.follow('subs', onSubtitles)
        Lampa.PlayerVideo.listener.follow('destroy', onVideoDestroy)

        return true
    }

    state.enabled = enabled
    state.remember = remember
    state.capture = captureSelections
    state.clear = clearPreferences
    state.preferences = loadPreferences

    installHooks()

    setInterval(captureSelections, 1000)

    if (window.appready) installSettings()
    else if (window.Lampa && Lampa.Listener && typeof Lampa.Listener.follow === 'function') {
        Lampa.Listener.follow('app', function (event) {
            if (event.type === 'ready') installSettings()
        })
    }

    console.log(PLUGIN_NAME, 'started', PLUGIN_VERSION)
})()
